// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvgBPJ-P20Ni30YSR13p06RZQUFD0X5g',
    appId: '1:726060120093:web:b32fb105304d5f5a2a2ef4',
    messagingSenderId: '726060120093',
    projectId: 'digi-worm',
    authDomain: 'digi-worm.firebaseapp.com',
    storageBucket: 'digi-worm.firebasestorage.app',
    measurementId: 'G-M5W0S78CSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqePHqki1M55vnLyDUeS0UwW_XRojQU8',
    appId: '1:726060120093:android:8748fea7f4bd7e632a2ef4',
    messagingSenderId: '726060120093',
    projectId: 'digi-worm',
    storageBucket: 'digi-worm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkz0cMAR7ZcMW8PuGc13X2u2OGf_Rd1FU',
    appId: '1:726060120093:ios:785462452dd2354c2a2ef4',
    messagingSenderId: '726060120093',
    projectId: 'digi-worm',
    storageBucket: 'digi-worm.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkz0cMAR7ZcMW8PuGc13X2u2OGf_Rd1FU',
    appId: '1:726060120093:ios:785462452dd2354c2a2ef4',
    messagingSenderId: '726060120093',
    projectId: 'digi-worm',
    storageBucket: 'digi-worm.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBvgBPJ-P20Ni30YSR13p06RZQUFD0X5g',
    appId: '1:726060120093:web:4963664de123545c2a2ef4',
    messagingSenderId: '726060120093',
    projectId: 'digi-worm',
    authDomain: 'digi-worm.firebaseapp.com',
    storageBucket: 'digi-worm.firebasestorage.app',
    measurementId: 'G-9K3LBJJREQ',
  );
}
